name: Setup Nix
description: Install Nix and load dev environment
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@51f3067b56fe8ae331890c77d4e454f6d60615ff # v31.10.2
      with:
        github_access_token: ${{ github.token }}

    - name: Cache Nix store
      uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7.0.2
      with:
        primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}-

    - name: Load Nix development environment
      shell: bash
      run: nix develop --command true
